name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Minimal code or steps to reproduce the issue.
      placeholder: |
        1. Create client with...
        2. Call method...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: If applicable, provide a minimal code example.
      render: go

  - type: textarea
    id: error
    attributes:
      label: Error Output
      description: Paste any error messages or stack traces.
      render: text

  - type: input
    id: sdk-version
    attributes:
      label: SDK Version
      description: Which version of go-thalex are you using?
      placeholder: "v0.1.0"
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: Output of `go version`
      placeholder: "go1.23.0 darwin/arm64"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "macOS 15, Ubuntu 24.04, Windows 11"

  - type: dropdown
    id: api
    attributes:
      label: API Type
      options:
        - REST
        - WebSocket
        - Both
        - Not applicable

  - type: dropdown
    id: network
    attributes:
      label: Network
      options:
        - Testnet
        - Production
        - Both

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem.
